### PR TITLE
add stackdump subcommand, update dev docs

### PR DESCRIPTION
**Pull request by rosskirkpat**
- add a new stackdump subcommand that allows an end-user to manually trigger the stackdump goroutine that was already built in to wins when it is running as a service
- add documentation for how to run wins locally as a service with locally-compiled wins binaries
- remove the use of `os.TempDir()` in pkg/profilings/stack.go

Notes:
there is now a new dependency https://github.com/iamacarpet/go-win64api for wins

### CODE REVIEW

**Comment by rosskirkpat** [comment]
Validation:

run `wins.exe --debug stackdump` after created wins as a service by following the new developer docs section

```console
time="2021-12-21T16:58:33-05:00" level=debug msg="findWinsProcess: found trimmed process [wins]"
time="2021-12-21T16:58:33-05:00" level=info msg="Found process [wins] with pid [31176]"
time="2021-12-21T16:58:33-05:00" level=debug msg="Confirmed that process 31176 is running."
time="2021-12-21T16:58:33-05:00" level=debug msg=Finished
```

Event viewer (Application log, rancher-wins provider)

```console
SetupStackDumps: dumped stacks to [C:\Windows\system32\rancher-wins.31176.stacks.log]
```

Here is an excerpt from `C:\Windows\system32\rancher-wins.31176.stacks.log` 
```log
...
goroutine 51 [chan receive]:
github.com/rancher/wins/cmd/server/app.(*serviceHandler).Execute(0xc000195a40, 0xc0007aa760, 0x1, 0x1, 0xc00071a7e0, 0xc00071a840, 0x0)
	C:/Users/rosskirk/repos/wins/cmd/server/app/run_service.go:263 +0x19a
golang.org/x/sys/windows/svc.serviceMain.func2(0xc0007aa760, 0x1, 0x1, 0xc00071a7e0, 0xc00071a840, 0xc00071a8a0)
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/golang.org/x/sys@v0.0.0-20211107104306-e0b2ad06fe42/windows/svc/service.go:233 +0x72
created by golang.org/x/sys/windows/svc.serviceMain
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/golang.org/x/sys@v0.0.0-20211107104306-e0b2ad06fe42/windows/svc/service.go:232 +0x2d3

goroutine 67 [semacquire]:
sync.runtime_Semacquire(0xc000342c10)
	c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000342c08)
	c:/go/src/sync/waitgroup.go:130 +0x6b
golang.org/x/sync/errgroup.(*Group).Wait(0xc000342c00, 0xc00029e1a0, 0x1e24e60)
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:40 +0x38
github.com/rancher/wins/pkg/apis.(*Server).Serve(0xc000462180, 0x1e24e60, 0xc0007057c0, 0x0, 0x0)
	C:/Users/rosskirk/repos/wins/pkg/apis/api.go:61 +0x25d
github.com/rancher/wins/cmd/server/app.(*serviceHandler).Execute.func1(0xc000195a40, 0x1e24e60, 0xc0007057c0)
	C:/Users/rosskirk/repos/wins/cmd/server/app/run_service.go:249 +0x4a
created by github.com/rancher/wins/cmd/server/app.(*serviceHandler).Execute
	C:/Users/rosskirk/repos/wins/cmd/server/app/run_service.go:248 +0x105

goroutine 69 [select]:
github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc00001e000, 0xc0001b5800, 0x0, 0x0, 0x1df24a0, 0x27c56f8, 0x0, 0x0, 0x0)
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/github.com/!microsoft/go-winio@v0.4.16/file.go:194 +0x14b
github.com/Microsoft/go-winio.connectPipe(0xc00001e000, 0x0, 0x0)
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/github.com/!microsoft/go-winio@v0.4.16/pipe.go:479 +0xe5
github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc0007ea120, 0xc00001e000)
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/github.com/!microsoft/go-winio@v0.4.16/pipe.go:369 +0x32
created by github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
	C:/Users/rosskirk/go-1.17.2-workspace/pkg/mod/github.com/!microsoft/go-winio@v0.4.16/pipe.go:368 +0xc5
...
```

**Comment by rosskirkpat** [comment]
https://github.com/rancher/windows/issues/147

**Review by phillipsj — APPROVED** [review]
LGTM!

**Review by phillipsj — APPROVED** [review]
LGTM!

**Pull request merged**
